### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by abejfehr**

### CODE REVIEW

**Review by evancloutier — CHANGES_REQUESTED** [review]
nah

**Review by evancloutier — CHANGES_REQUESTED** [review]
nice try

**Review by evancloutier — CHANGES_REQUESTED** [review]
biiiiiiiitch

**Review by evancloutier — CHANGES_REQUESTED** [review]
Really @abejfehr? Please evaluate our business needs and think of a better solution.

**Comment by abejfehr** [comment]
I'm closing these, we can reopen if we need to test again

**Pull request closed without merging**
